language: python

python:
  - "3.7"

services:
  - postgresql

addons:
  - postgresql: "10.3"

env:
  global:
    - DATABASE_URL=postgres://user_name:user_password@localhost:5432/db_name
    - SECRET_KEY='$(#98&$^!nf&lhp&6r6+o2$luf)ps9&%gs*r3mvcz1^4bfv@v3'
    - ALLOWED_HOSTS='*'

before_install:
  - TEMPLATE_PATH=`pwd`
  - mkdir ../testing && cd ../testing
  - pip install django  # "django-admin" needs to be there before dependencies are installed
  - django-admin startproject --template=${TEMPLATE_PATH} --extension=po,yml,md,py testing .

install: "pip install -r requirements.txt coverage"

before_script:
  - psql -c "CREATE DATABASE db_name;" -U postgres
  - psql -c "CREATE USER user_name WITH PASSWORD 'user_password' CREATEDB;" -U postgres

script:
  - coverage run manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
